// ─────────────────────────────────────────────────────────────────────────────
//  firebase_options.dart — PLACEHOLDER
//
//  This file is generated by the FlutterFire CLI:
//    dart pub global activate flutterfire_cli
//    flutterfire configure
//
//  HOW TO GENERATE THE REAL FILE:
//  ──────────────────────────────
//  1. Go to https://console.firebase.google.com and create a project
//     named "wordlearn" (or any name you choose).
//  2. Add an Android app:
//       Package name: com.wordlearn.word_learn
//  3. Add an iOS app:
//       Bundle ID: com.wordlearn.wordLearn
//  4. Run in this project root:
//       dart pub global activate flutterfire_cli
//       flutterfire configure
//  5. Commit the generated firebase_options.dart and google-services.json
//     (Android) / GoogleService-Info.plist (iOS).
//
//  Until then, this stub allows the project to compile in dev mode.
//  The app will crash on startup if devModeSkipFirebase is not handled,
//  so AppConfig.devModeSkipFirebase = true guards Firebase.initializeApp()
//  in main.dart until the real config is present.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── REPLACE THESE VALUES after running `flutterfire configure` ────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ANDROID_API_KEY',
    appId: 'REPLACE_WITH_ANDROID_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_IOS_API_KEY',
    appId: 'REPLACE_WITH_IOS_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
    iosBundleId: 'com.wordlearn.wordLearn',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_WEB_API_KEY',
    appId: 'REPLACE_WITH_WEB_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
  );
}
